# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Upload dotnet package

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set Version Variable
      if: ${{ github.ref_type == 'tag' }}
      env:
        TAG: ${{ github.ref_name }}
      run: echo "VERSION=${TAG#v}" >> $GITHUB_ENV
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release /p:Version=$VERSION
    - name: Pack NuGet package
      run: dotnet pack --configuration Release --output ./nupkg /p:PackageVersion=$VERSION
      if: success() && github.ref_type == 'tag'      
    - name: Publish NuGet package to GitHub Packages
      run: dotnet nuget push ./nupkg/*.nupkg --source https://nuget.pkg.github.com/lelekaihor/index.json --api-key ${{ secrets.GITHUB_TOKEN }}
      if: success() && github.ref_type == 'tag'
    - name: Publish NuGet package
      run: dotnet nuget push ./nupkg/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
      if: success() && github.ref_type == 'tag'
